### ISSUE TITLE
Passive Scalar Issue In GR

### ISSUE THREAD

**Issue by smressle** [PrincetonUniversity/athena-public-version#44] opened 2020-04-04 07:27 UTC
Hi all,

It looks to me like there might be an error in the eos_scalars.cpp functions when using relativity.  Since the conservation equation is 

d_t (gdet rho u^t r) + d_i (gdet rho u^i r) = 0

 shouldn't the conservative scalar s be [s = density * u^t  * r] instead of just [s = density * r] (that is, there is a missing factor of the time component of the contravariant four-velocity)? 

I could be missing something in the code.

Sean

**Comment by c-white** [comment] 2020-04-04 07:59
This is a known bug in the development version. A [fix was developed 2019-09-16](https://github.com/PrincetonUniversity/athena/pull/297), but is on hold indefinitely because of other changes due to be made. Hopefully it will be included in the next public release. Until then, contact me and I can figure out how to patch the public version.

**Comment by c-white** [comment] 2020-04-29 21:39
Here is the fix for anyone who might be interested. It is applied on top of commit d5350951 from 2019-10-15.

1. Download [scalar_fix.patch](https://github.com/PrincetonUniversity/athena-public-version/files/4554702/scalar_fix.patch.txt) (rename it to remove `.txt`) into the top of the Athena directory.
2. `git apply scalar_fix.patch`
3. `cd tst/regression`
4. `./run_tests.py scalars/sr_hydro_scalars`

If the test passes, the fix should be working. It should take less than a minute to run.

Note: this will create `tst/regression/scripts/tests/scalars/sr_hydro_scalars.py`, and it will modify

```
inputs/hydro_sr/athinput.mb_1
inputs/hydro_sr/athinput.mb_2
inputs/hydro_sr/athinput.mb_3
inputs/hydro_sr/athinput.mb_4
src/athena.hpp
src/bvals/bvals.cpp
src/bvals/bvals_refine.cpp
src/eos/eos.hpp
src/eos/eos_scalars.cpp
src/hydro/srcterms/hydro_srcterms.cpp
src/hydro/srcterms/hydro_srcterms.hpp
src/mesh/mesh.cpp
src/pgen/gr_shock_tube.cpp
src/pgen/strat.cpp
src/task_list/time_integrator.cpp
```

**Closed as completed by c-white** 2020-04-29 21:39 UTC
Labels: bug, GR/SR
