### ISSUE TITLE
Unexpected behavior in 3D linear wave tests with strong B field

### ISSUE THREAD

**Issue by XihZhao** [PrincetonUniversity/athena-public-version#68] opened 2020-12-07 06:19 UTC
Dear contributors,

I found Athena++ sometimes does not behave as expected when I ran 3D linear wave tests with strong magnetic field (B=6). 
Specifically, the wave amplitude of the initial perturbation could undergo a blow-up at the end of some cases, instead of keeping constant, or damping due to the numerical viscosity.

I imposed a magnetic field |B|=6 in the problem generator linear_wave.cpp, with the orientation aligned or transverse to the wave vector k. The resolution here is by default ~20 cells per wave length, as in the athinput.linear_wave3d file. I tried simulations with different EOS, reconstruction orders and solvers. In each case, I tested Alfvén wave, fast and slow magneto sonic waves and made a plot of their ratios to the initial amplitude as a function of time. Below are some results, the titles explain those settings.

![github](https://user-images.githubusercontent.com/59157605/101313688-a683c900-3891-11eb-814f-cd9b0be325b3.png)
![github1](https://user-images.githubusercontent.com/59157605/101313702-b13e5e00-3891-11eb-93e3-28b091a5f1f4.png)
![github2](https://user-images.githubusercontent.com/59157605/101313748-d9c65800-3891-11eb-9e49-733053a60601.png)
![githuba](https://user-images.githubusercontent.com/59157605/101313758-e34fc000-3891-11eb-98a3-dad54642bb76.png)

Since the adiabatic EOS gives similar results, I just omit them here. The first plot demonstrates a very suspicious behavior, which does not show up in a 2D test where all other ingredients remain the same:
![2D git](https://user-images.githubusercontent.com/59157605/101314934-8dc8e280-3894-11eb-9eb2-ab20efa5b043.png)

Then I rotate the wave vector k in the user's coordinate frame to mimic a 2D situation in 3D simulation, however the blow-up still occurs, but with a different type of wave:
![degenerate](https://user-images.githubusercontent.com/59157605/101315193-0def4800-3895-11eb-97a0-c4830d7395f1.png)

Please note that, in all the above cases, I set B field parallel to the wave vector k when I test Alfvén and slow wave, while B is perpendicular to k in the fast magnetosonic case. And the wave vector k is oblique to the user's frame by default (except in the degenerate case above). I also tried to run the first case with the B field oblique to wave vector k as in the default linear_wave.cpp file, and the crazy increase didn't happen:
![oblique git](https://user-images.githubusercontent.com/59157605/101315649-f2387180-3895-11eb-9763-b73e95c64286.png)
So maybe the blow-up is a flaw instead of a bug, due to the somewhat tough conditions I imposed. But let me report it here anyway.

Thanks in advance for help.

**Comment by felker** [comment] 2020-12-07 17:32
Unless I am misremembering the problem, I don't think you can simply scale up the magnitude of the magnetic field while preserving the initial condition being pure eigenmodes of the linearized MHD system. See Appendix A of https://arxiv.org/pdf/astro-ph/0501557.pdf 

~Also, the linearization approximation may no longer be valid when the magnetic field is that strong.~

**Comment by felker** [comment] 2020-12-07 20:20
Can you show me exactly how you apply the magnetic field in the code? What are the eigenvalues `ev[]` returned by `Eigensystem()`?

How are you computing the ratio of amplitudes of the initial and translated wave? Are you taking the maximum amplitudes?

It is a bit hard to tell if the code is not working correctly from your plots. It would be better to only compute error or show the profile with respect to the initial profile after an integer number of wave periods. 

I would expect the fast and slow magnetosonic waves to eventually stop appearing like their initial profiles due to wave steepening. So the first two plots aren't too concerning if the wavespeed is much faster than the default. The Alfven wave blowup is more concerning, I think.

I bet the differences you are observing in the 3D and 2D cases are because the problem generator automatically adjusts `lambda` based on the mesh dimensionality and size.

**Comment by X1Hu1Zhao** [comment] 2020-12-08 13:16
Thank you @felker for your response. Let me first answer you about how I operated.

In the default linear_wave.cpp, from line 154~156, some values are assigned to bx0, by0 and bz0. I think setting these values sets the background field, according to the subsequent calculation in ProblemGenerator. I set bx0=6.0 (others=0) to apply a B field parallel to wave vector k, and by0=6 for perpendicular B.

I made those plots by picking up the maximum value from the velocity field at each moment, and divided it by the initial maximum velocity. As for the wavelengths in 2D and 3D cases, by default they are all lambda=1, and when I rotate wave vector in 3D case, I changed the simulation box size accordingly so the wavelength is still 1.

I am not sure how to compute errors, do you mean turning the "compute_error" on in the athinput file? If so, I noticed in the .dat file generated, all the isothermal cases give out a RMS-L1-Error ~ 6.0, while adiabatic cases give out a RMS-L1-Error ~ 1e-6. Below I made three x-y slices of the velocity field taken at three moments:initial time, the moment when it started to get unstable (t ~ 1.5T), and late time (t ~ 3T). This case is the fast magnetosonic curve in the first plot,
![pro1](https://user-images.githubusercontent.com/59157605/101487642-6dcf1700-3999-11eb-8876-32ca9f16bee7.png)
![pro2](https://user-images.githubusercontent.com/59157605/101487656-7293cb00-3999-11eb-9d16-9da2701afb63.png)
![pro3](https://user-images.githubusercontent.com/59157605/101487667-74f62500-3999-11eb-8cf4-681d2d4842d8.png)
hope this can help. (The x and y coordinates in the plot are just index of cells)

And I don't quite understand why the eigensystem routine can not apply here. In the linear_wave.cpp file, line 167, the Eigensystem function is called after I set bx0, by0 and bz0. And these three numbers are input parameters of the Eigensystem function. So I suppose the design here is to calculate eigenmodes accordingly?

**Comment by felker** [comment] 2021-01-20 08:14
> In the default linear_wave.cpp, from line 154~156, some values are assigned to bx0, by0 and bz0. I think setting these values sets the background field, according to the subsequent calculation in ProblemGenerator. 

This is correct, and indeed, the `Eigensystem()` routine is completely general and you can use it to linearize around any valid background fluid state.

However, your choices of background B-field configurations, as I understand them:
```
  bx0 = 0.0;
  by0 = 6.0;
  bz0 = 0.0;
```
for fast magnetosonic wave tests and 
```
  bx0 = 6.0;
  by0 = 0.0;
  bz0 = 0.0;
```
for Alfven wave tests, are suboptimal choices. E.g. in the first case, the eigenvalues and right eigenvectors are:
```
ev[0] = -6.08276
ev[1] = 0
ev[2] = 0
ev[3] = 0
ev[4] = 0
ev[5] = 6.08276
rem[0][0] = 0.164399
rem[1][0] = -1
rem[2][0] = 0
rem[3][0] = 0
rem[4][0] = 0.986394
rem[5][0] = 0

rem[0][1] = 0
rem[1][1] = 0
rem[2][1] = -0
rem[3][1] = 1
rem[4][1] = -0
rem[5][1] = 1

rem[0][2] = 0.986394
rem[1][2] = 0
rem[2][2] = -1
rem[3][2] = 0
rem[4][2] = -0.164399
rem[5][2] = 0

rem[0][3] = 0.986394
rem[1][3] = 0
rem[2][3] = 1
rem[3][3] = 0
rem[4][3] = -0.164399
rem[5][3] = 0

rem[0][4] = 0
rem[1][4] = 0
rem[2][4] = 0
rem[3][4] = -1
rem[4][4] = -0
rem[5][4] = 1

rem[0][5] = 0.164399
rem[1][5] = 1
rem[2][5] = -0
rem[3][5] = 0
rem[4][5] = 0.986394
rem[5][5] = 0
```
So obviously the Alfven and slow magnetosonic waves have the same wavespeeds. 

The oblique background B-field that is in `linear_wave.cpp` by default was chosen very carefully to get well-separated wave speeds and to break symmetries in the B-field orientation. If you want to repeat this test with a stronger B-field, I would suggest scaling up these components up so that you get similarly well-separated wave speeds. You can then use the same background field for all three wave modes. 

I was able to reproduce your first plot, but I am not convinced that it demonstrates a problem with the code.

In this system, the wave amplitude is 1e-7 and the background is O(1), so if the non-linear mode coupling modifies the wave, there is sufficient "free energy" to cause the velocity profile to grow as in your plots. While the plasma beta is O(1/100) and is neither easy nor hard, I postulate that the linearized approximation breaks down past t=3 (or 18 wave periods) for the particular numerical diffusion from PLM + HLLD. That is many more wave periods than I have ever run the test for with the default background field, whose fast wave is 3x slower than yours. I can't recall how to quantify how long one can reasonably expect the nonlinear wave coupling and steepening effects to be negligible for this problem. Perhaps this background field with the degenerate wave modes is more susceptible to this mode mixing?

Did you try HLLE in addition to HLLD and Roe? I briefly tested it and it seemed to be fine, like Roe.

With regards to  the `compute_error` option in the athinput file, the outputted quantity is only meaningful if the simulation terminates at a `tlim` that exactly matches an integer multiple of the wave period. So for your observation that:
> all the isothermal cases give out a RMS-L1-Error ~ 6.0

I assume this is because the fast magnetosonic wave speed in this case did not match up with your `tlim`. 

>Then I rotate the wave vector k in the user's coordinate frame to mimic a 2D situation in 3D simulation, however the blow-up still occurs, but with a different type of wave:

I am curious about exactly what lines of code you changed for this test.

If the code is working with rotated (non-degenerate) fields, I think it is fine.

**Closed as completed by felker** 2021-01-20 08:14 UTC

**Comment by X1Hu1Zhao** [comment] 2021-01-24 07:14
Okay thank you @felker for the detailed and responsible explanation. I agree with you, the code is fine, and I think you are right about my `tlim` mismatching wave speed. And thanks for the suggestion.

To rotate the wave vector, I changed the input file, setting `ang_2 = 0.0`, and left `ang_3` the same as 2D case. Then I changed the box size according to the 2D input file so that the wavelength remains unaltered.
